#!/bin/bash

set -e # Exit if any simple command fails

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root!" 1>&2
	exit 1
fi

echo "This is the installer script for dirmenu, a bash menu a menu based solely"
echo "on a given directory's structure and some configuration files."
echo
echo "You can find more information about it at http://github.com/andrefs/dirmenu"
echo

if [ -z "$DMINSTALLDIR" ]; then
    export DMINSTALLDIR="/opt/dirmenu"
fi

echo "*** Creating directory '$DMINSTALLDIR'..."
mkdir -p "$DMINSTALLDIR"

echo "*** Cloning gb-sysmenu Git repository to '$DMINSTALLDIR'..."
git clone git://github.com/andrefs/dirmenu.git "$DMINSTALLDIR" 2>/dev/null

bash "$DMINSTALLDIR"/dirmenu_generate
cp "$DMINSTALLDIR"/dirmenu /usr/local/bin/dirmenu
chmod +x /usr/local/bin/dirmenu

echo "$0 is now installed!" >&2

