#!/bin/bash

set -e # Exit if any simple command fails

cat <<- END > /tmp/dirmenu
#!/bin/bash
export DMINSTALLDIR="$DMINSTALLDIR"

END
cat "$DMINSTALLDIR"/dirmenu.skel >> /tmp/dirmenu

mv /tmp/dirmenu /usr/local/bin/dirmenu
chmod +x /usr/local/bin/dirmenu
echo "dirmenu is now installed!" >&2
exit 0

